### PR TITLE
Use nice, unobtrusive GitHub-styled icon as button

### PR DESCRIPTION
**Pull request by Cito**
Includes the following changes:

- text buttons replaced with icons
- darker color while inactive for less distraction
- also hide button until hovering over code block
- fix TypeScript issues
- use SCSS to simplify CSS

This is essentially jdbrice/obsidian-code-block-copy#13.

Thanks to @tdharris for the improvements.

### CODE REVIEW

**Comment by superDuperCyberTechno** [comment]
I'll have a look-see, ASAP. Thanks for the work.

**Comment by superDuperCyberTechno** [comment]
What exactly are the _TypeScript issues_? As far as I can tell it's only the indentation?

**Comment by Cito** [comment]
> What exactly are the _TypeScript issues_? As far as I can tell it's only the indentation?

Some variables like `pre` had no type, so my IDE and the build process warned when accessing certain properties. I have type casted it to the proper HTML element, so that these errors disappear.

**Comment by Cito** [comment]
Regarding the indentation, I have formatted everything with [prettier](https://prettier.io/). Sorry, this should have been done separately.

**Comment by superDuperCyberTechno** [comment]
> Regarding the indentation, I have formatted everything with [prettier](https://prettier.io/). Sorry, this should have been done separately.

No problem. I'm just lazy, haven't bothered with setting up proper JS indentation. Just went with the default 4 spaces. I'll look into making Vim behave so this doesn't become a recurring PR...

**Pull request merged**
